#
# ~/.bashrc
#

# Suggested packages:
# bat tree xclip ncdu lsof rsync ranger pv borg entr shuf
# curl wget dd

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Make profile env vars do be reloaded every time new shell is started
[[ -f ~/.profile ]] && . ~/.profile

### VARIABLES (CONFIGURATION ONLY) ###
PS1="\[\033[38;5;3m\][\[$(tput sgr0)\]\[\033[38;5;11m\]\u\[$(tput sgr0)\]\[\033[38;5;15m\]@\h \[$(tput sgr0)\]\[\033[38;5;9m\]\w\[$(tput sgr0)\]\[\033[38;5;3m\]]\[$(tput sgr0)\]\[\033[38;5;15m\] \\$ \[$(tput sgr0)\]"


### ALIAS ###
# General tools
alias h='cd $HOME'
alias l='ls'
alias ls='ls -l --color=auto'
alias cat='bat --plain --theme 1337'
alias mv='mv -i'
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."

# List used/free space in the filesystem
alias space='df -hT -x tmpfs -x devtmpfs'

# List the folder sizes in current dir, reversed ordered by size
alias sizes='du -h -d 1 . | sed "s/\.\///g" | sort -h -r'

# Express VPN
alias evpn="expressvpn"
alias evpns="expressvpn status"
alias evpnc="expressvpn connect"
alias evpnd="expressvpn disconnect"
alias evpnb="expressvpn disconnect ; expressvpn connect Brazil"
alias evpnn="expressvpn disconnect ; expressvpn connect Netherlands"
alias evpng="expressvpn disconnect ; expressvpn connect Germany"

# Generate SSH key
alias sshgen="ssh-keygen -t rsa -b 2048 -m pem"

# Pacman
alias pacs="pacman -Ss"
alias paci="sudo pacman -S"
alias pacu="sudo pacman -Syy"
alias pacup="sudo pacman -Syyu"
alias pacr="sudo pacman -Rns"
alias pacrc="sudo pacman -Rnsc"
alias pacd="pacman -Si"
alias paclast="grep -E '\[ALPM\]\ installed|\[ALPM\]\ reinstalled' /var/log/pacman.log | sort -r | bat"
alias pacq="pacman -Q"
alias pacqf="pacman -Ql"

# Git
# Following the alias standards from oh-my-zsh git plugin: https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/git
alias gst="git status"
alias gfa="git fetch --all --prune"
alias gaa="git add --all"
alias ga="git add"
alias gapa="git add --patch"
alias gca="git commit -v -a"
alias gcmsg="git commit -m" 
alias gcam="git commit -a -m"
alias gd="git diff"
alias gdca="git diff --cached"
alias gco="git checkout"
alias gcb="git checkout -b"
alias gcd="git checkout develop"
alias gcm="git checkout master"
alias glo="git log --oneline --decorate"
alias ggpush="git push"

# Vagrant
alias vs="vagrant status"
alias vss="vagrant ssh"
alias vu="vagrant up"
alias vh="vagrant halt"
alias vr="vagrant reload"


### FUNCTIONS ###
# Configures this script
config_bash()
{
    $EDITOR $HOME/.bashrc
}

# Configures environment variables
config_env()
{
    $EDITOR $HOME/.profile
}

# Configures inputrc file (Readline configuration)
config_inputrc()
{
    $EDITOR $HOME/.inputrc
}

# Configures the custom scripts held in scripts dir
config_script()
{
    if [ -z $1 ]; then
        return
    fi

    local filename="$1.sh"
    $EDITOR $HOME/.bash_scripts/$filename
}

# Configures the custom scripts held in scripts dir (private)
config_privscript()
{
    if [ -z $1 ]; then
        return
    fi
    echo $1

    local private_filename="priv_$1.sh"
    $EDITOR $HOME/.bash_scripts/$private_filename
}

config_lscript()
{
    (cd $HOME/.bash_scripts/ && /bin/ls *.sh)
}

config_vim()
{
    $EDITOR $HOME/.vimrc
}

# Finds file starting from current directory
# All parameters after the first one will be used as find parameters
f() {
    local filter="$1"
    shift
    find . -iname "*$filter*" $@
}

# Find the string content inside files using grep
r() {
    local filter="$1"
    if [ -z $1 ]; then
        echo "r: Please provide a filter pattern"
        return 1
    fi

    shift
    grep "$filter" $@ -R .
}

# Creates one or more folders and immediately change to the last of them
mkcd()
{
    mkdir -p "$@" && cd "$_"
}

# Takes the md5sum of all files in a given directory (recursively)
# and creates a file with them
# Useful for comparing directories, having done for both of then and
# comparing the text file with the hashes
# https://askubuntu.com/questions/421712/comparing-the-contents-of-two-directories
md5dir()
{
    if [ -z $1 ]; then
        echo "md5dir: Please provide the folder path"
        return 1
    fi

    dirname=$(basename $(readlink -f $1))

    find $1 -type f -exec md5sum {} + | sort -k 2 > ./${dirname}-md5sum-$(date +%Y-%m-%d_%H-%M).txt
}

# Find out number of lines per file and order them
fcount()
{
    if [ -z $1 ]; then
        echo "fcount: Please provide the folder path and filetype extension"
        return 1
    fi

    if [ -z $2 ]; then
        echo "fcount: Please provide the filetype extension"
        return 1
    fi
    extension="$2"

    find "$1" -name "*.${extension}" | xargs wc -l | head -n -2 | sort -b -n
}

# Copy the contents of a file to the clipboard (XA_CLIPBOARD)
copyfile()
{
    if [ -z $1 ]; then
        echo "md5dir: Please provide the folder path"
        return 1
    fi

    /bin/cat "$1" | xclip -selection clipboard
}

# External scripts
. $HOME/.bash_scripts/*.sh

